name = "skillbank-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
SUPABASE_URL = "https://eccwfcfoysauxnnsvcwn.supabase.co"

# 使用 wrangler secret put SUPABASE_ANON_KEY 设置
# SUPABASE_ANON_KEY = ""

[env.production]
name = "skillbank-api"

[env.dev]
name = "skillbank-api-dev"
